apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-mcp
  namespace: guardrails-dynamic
spec:
  parentRefs:
    - name: eg
      namespace: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: echo-mcp
          namespace: default
          port: 8000
