apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - presidio.yaml
  - echo-mcp.yaml
  - guardrail-adapter.yaml
  - gateway.yaml
  - httproute.yaml
  - reference-grant.yaml
  - ext-proc-policy.yaml
  - patch-policy.yaml
