apiVersion: v1
kind: Namespace
metadata:
  name: guardrails-dynamic
---
apiVersion: v1
kind: Namespace
metadata:
  name: guardrails-static
---
apiVersion: v1
kind: Namespace
metadata:
  name: guardrail-providers
