apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-routes-to-echo-mcp
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: guardrails-dynamic
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: guardrails-static
  to:
    - group: ""
      kind: Service
      name: echo-mcp
