apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: guardrail-extproc
  namespace: default
spec:
  extProc:
    - backendRefs:
        - name: guardrail-adapter-static
          namespace: guardrails
