apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../local

configMapGenerator:
  - name: guardrail-adapter-config
    namespace: guardrails
    files:
      - config.yaml

patches:
  - path: adapter-patch.yaml
    target:
      kind: Deployment
      name: guardrail-adapter
  - path: delete-patch-policy.yaml
    target:
      kind: EnvoyPatchPolicy
      name: guardrail-route-metadata
